title: Eric Cheney
description: Mechanical Engineering Student
site_title: '@Eric - Eric Cheney'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: EricCheney
blog_url: 
email: echeney456@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 