title: Eric Cheney
description: Mechanical Engineering Student
site_title: '@Eric - Eric Cheney'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: EricCheney
blog_url: https://www.nagekar.com
email: echeney456@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 